// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.BLL.Models;

namespace Task.BLL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210712211905_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task.BLL.Models.Exam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Exam");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EndDate = new DateTime(2021, 7, 13, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 1",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 2,
                            EndDate = new DateTime(2021, 7, 14, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 2",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 3,
                            EndDate = new DateTime(2021, 7, 15, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 3",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 4,
                            EndDate = new DateTime(2021, 7, 16, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 4",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 5,
                            EndDate = new DateTime(2021, 7, 17, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 5",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 6,
                            EndDate = new DateTime(2021, 7, 18, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 6",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 7,
                            EndDate = new DateTime(2021, 7, 19, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 7",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 8,
                            EndDate = new DateTime(2021, 7, 20, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 8",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 9,
                            EndDate = new DateTime(2021, 7, 21, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 9",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        },
                        new
                        {
                            ID = 10,
                            EndDate = new DateTime(2021, 7, 22, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694),
                            Name = "Exam 10",
                            StartDate = new DateTime(2021, 7, 12, 23, 19, 4, 694, DateTimeKind.Local).AddTicks(6694)
                        });
                });

            modelBuilder.Entity("Task.BLL.Models.ExamQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Answer")
                        .HasColumnType("bit");

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.ToTable("ExamQuestion");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Answer = true,
                            ExamID = 1,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 2,
                            Answer = true,
                            ExamID = 1,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 3,
                            Answer = true,
                            ExamID = 1,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 4,
                            Answer = true,
                            ExamID = 1,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 5,
                            Answer = true,
                            ExamID = 1,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 6,
                            Answer = false,
                            ExamID = 1,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 7,
                            Answer = false,
                            ExamID = 1,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 8,
                            Answer = false,
                            ExamID = 1,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 9,
                            Answer = false,
                            ExamID = 1,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 10,
                            Answer = false,
                            ExamID = 1,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 11,
                            Answer = true,
                            ExamID = 2,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 12,
                            Answer = true,
                            ExamID = 2,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 13,
                            Answer = true,
                            ExamID = 2,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 14,
                            Answer = true,
                            ExamID = 2,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 15,
                            Answer = true,
                            ExamID = 2,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 16,
                            Answer = false,
                            ExamID = 2,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 17,
                            Answer = false,
                            ExamID = 2,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 18,
                            Answer = false,
                            ExamID = 2,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 19,
                            Answer = false,
                            ExamID = 2,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 20,
                            Answer = false,
                            ExamID = 2,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 21,
                            Answer = true,
                            ExamID = 3,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 22,
                            Answer = true,
                            ExamID = 3,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 23,
                            Answer = true,
                            ExamID = 3,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 24,
                            Answer = true,
                            ExamID = 3,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 25,
                            Answer = true,
                            ExamID = 3,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 26,
                            Answer = false,
                            ExamID = 3,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 27,
                            Answer = false,
                            ExamID = 3,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 28,
                            Answer = false,
                            ExamID = 3,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 29,
                            Answer = false,
                            ExamID = 3,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 30,
                            Answer = false,
                            ExamID = 3,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 31,
                            Answer = true,
                            ExamID = 4,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 32,
                            Answer = true,
                            ExamID = 4,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 33,
                            Answer = true,
                            ExamID = 4,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 34,
                            Answer = true,
                            ExamID = 4,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 35,
                            Answer = true,
                            ExamID = 4,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 36,
                            Answer = false,
                            ExamID = 4,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 37,
                            Answer = false,
                            ExamID = 4,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 38,
                            Answer = false,
                            ExamID = 4,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 39,
                            Answer = false,
                            ExamID = 4,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 40,
                            Answer = false,
                            ExamID = 4,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 41,
                            Answer = true,
                            ExamID = 5,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 42,
                            Answer = true,
                            ExamID = 5,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 43,
                            Answer = true,
                            ExamID = 5,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 44,
                            Answer = true,
                            ExamID = 5,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 45,
                            Answer = true,
                            ExamID = 5,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 46,
                            Answer = false,
                            ExamID = 5,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 47,
                            Answer = false,
                            ExamID = 5,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 48,
                            Answer = false,
                            ExamID = 5,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 49,
                            Answer = false,
                            ExamID = 5,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 50,
                            Answer = false,
                            ExamID = 5,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 51,
                            Answer = true,
                            ExamID = 6,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 52,
                            Answer = true,
                            ExamID = 6,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 53,
                            Answer = true,
                            ExamID = 6,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 54,
                            Answer = true,
                            ExamID = 6,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 55,
                            Answer = true,
                            ExamID = 6,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 56,
                            Answer = false,
                            ExamID = 6,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 57,
                            Answer = false,
                            ExamID = 6,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 58,
                            Answer = false,
                            ExamID = 6,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 59,
                            Answer = false,
                            ExamID = 6,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 60,
                            Answer = false,
                            ExamID = 6,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 61,
                            Answer = true,
                            ExamID = 7,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 62,
                            Answer = true,
                            ExamID = 7,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 63,
                            Answer = true,
                            ExamID = 7,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 64,
                            Answer = true,
                            ExamID = 7,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 65,
                            Answer = true,
                            ExamID = 7,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 66,
                            Answer = false,
                            ExamID = 7,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 67,
                            Answer = false,
                            ExamID = 7,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 68,
                            Answer = false,
                            ExamID = 7,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 69,
                            Answer = false,
                            ExamID = 7,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 70,
                            Answer = false,
                            ExamID = 7,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 71,
                            Answer = true,
                            ExamID = 8,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 72,
                            Answer = true,
                            ExamID = 8,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 73,
                            Answer = true,
                            ExamID = 8,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 74,
                            Answer = true,
                            ExamID = 8,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 75,
                            Answer = true,
                            ExamID = 8,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 76,
                            Answer = false,
                            ExamID = 8,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 77,
                            Answer = false,
                            ExamID = 8,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 78,
                            Answer = false,
                            ExamID = 8,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 79,
                            Answer = false,
                            ExamID = 8,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 80,
                            Answer = false,
                            ExamID = 8,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 81,
                            Answer = true,
                            ExamID = 9,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 82,
                            Answer = true,
                            ExamID = 9,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 83,
                            Answer = true,
                            ExamID = 9,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 84,
                            Answer = true,
                            ExamID = 9,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 85,
                            Answer = true,
                            ExamID = 9,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 86,
                            Answer = false,
                            ExamID = 9,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 87,
                            Answer = false,
                            ExamID = 9,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 88,
                            Answer = false,
                            ExamID = 9,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 89,
                            Answer = false,
                            ExamID = 9,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 90,
                            Answer = false,
                            ExamID = 9,
                            QuestionType = 1,
                            Text = "Question 10"
                        },
                        new
                        {
                            ID = 91,
                            Answer = true,
                            ExamID = 10,
                            QuestionType = 0,
                            Text = "Question 1"
                        },
                        new
                        {
                            ID = 92,
                            Answer = true,
                            ExamID = 10,
                            QuestionType = 0,
                            Text = "Question 2"
                        },
                        new
                        {
                            ID = 93,
                            Answer = true,
                            ExamID = 10,
                            QuestionType = 0,
                            Text = "Question 3"
                        },
                        new
                        {
                            ID = 94,
                            Answer = true,
                            ExamID = 10,
                            QuestionType = 0,
                            Text = "Question 4"
                        },
                        new
                        {
                            ID = 95,
                            Answer = true,
                            ExamID = 10,
                            QuestionType = 0,
                            Text = "Question 5"
                        },
                        new
                        {
                            ID = 96,
                            Answer = false,
                            ExamID = 10,
                            QuestionType = 1,
                            Text = "Question 6"
                        },
                        new
                        {
                            ID = 97,
                            Answer = false,
                            ExamID = 10,
                            QuestionType = 1,
                            Text = "Question 7"
                        },
                        new
                        {
                            ID = 98,
                            Answer = false,
                            ExamID = 10,
                            QuestionType = 1,
                            Text = "Question 8"
                        },
                        new
                        {
                            ID = 99,
                            Answer = false,
                            ExamID = 10,
                            QuestionType = 1,
                            Text = "Question 9"
                        },
                        new
                        {
                            ID = 100,
                            Answer = false,
                            ExamID = 10,
                            QuestionType = 1,
                            Text = "Question 10"
                        });
                });

            modelBuilder.Entity("Task.BLL.Models.MultipleChoiceQuestionAnswer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamQuestionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ExamQuestionID");

                    b.ToTable("MultipleChoiceQuestionAnswer");

                    b.HasData(
                        new
                        {
                            ID = 11,
                            ExamQuestionID = 6,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 12,
                            ExamQuestionID = 6,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 13,
                            ExamQuestionID = 7,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 14,
                            ExamQuestionID = 7,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 15,
                            ExamQuestionID = 8,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 16,
                            ExamQuestionID = 8,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 17,
                            ExamQuestionID = 9,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 18,
                            ExamQuestionID = 9,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 19,
                            ExamQuestionID = 10,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 20,
                            ExamQuestionID = 10,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 31,
                            ExamQuestionID = 16,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 32,
                            ExamQuestionID = 16,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 33,
                            ExamQuestionID = 17,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 34,
                            ExamQuestionID = 17,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 35,
                            ExamQuestionID = 18,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 36,
                            ExamQuestionID = 18,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 37,
                            ExamQuestionID = 19,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 38,
                            ExamQuestionID = 19,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 39,
                            ExamQuestionID = 20,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 40,
                            ExamQuestionID = 20,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 51,
                            ExamQuestionID = 26,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 52,
                            ExamQuestionID = 26,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 53,
                            ExamQuestionID = 27,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 54,
                            ExamQuestionID = 27,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 55,
                            ExamQuestionID = 28,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 56,
                            ExamQuestionID = 28,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 57,
                            ExamQuestionID = 29,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 58,
                            ExamQuestionID = 29,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 59,
                            ExamQuestionID = 30,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 60,
                            ExamQuestionID = 30,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 71,
                            ExamQuestionID = 36,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 72,
                            ExamQuestionID = 36,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 73,
                            ExamQuestionID = 37,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 74,
                            ExamQuestionID = 37,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 75,
                            ExamQuestionID = 38,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 76,
                            ExamQuestionID = 38,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 77,
                            ExamQuestionID = 39,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 78,
                            ExamQuestionID = 39,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 79,
                            ExamQuestionID = 40,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 80,
                            ExamQuestionID = 40,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 91,
                            ExamQuestionID = 46,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 92,
                            ExamQuestionID = 46,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 93,
                            ExamQuestionID = 47,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 94,
                            ExamQuestionID = 47,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 95,
                            ExamQuestionID = 48,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 96,
                            ExamQuestionID = 48,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 97,
                            ExamQuestionID = 49,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 98,
                            ExamQuestionID = 49,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 99,
                            ExamQuestionID = 50,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 100,
                            ExamQuestionID = 50,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 111,
                            ExamQuestionID = 56,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 112,
                            ExamQuestionID = 56,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 113,
                            ExamQuestionID = 57,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 114,
                            ExamQuestionID = 57,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 115,
                            ExamQuestionID = 58,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 116,
                            ExamQuestionID = 58,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 117,
                            ExamQuestionID = 59,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 118,
                            ExamQuestionID = 59,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 119,
                            ExamQuestionID = 60,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 120,
                            ExamQuestionID = 60,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 131,
                            ExamQuestionID = 66,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 132,
                            ExamQuestionID = 66,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 133,
                            ExamQuestionID = 67,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 134,
                            ExamQuestionID = 67,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 135,
                            ExamQuestionID = 68,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 136,
                            ExamQuestionID = 68,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 137,
                            ExamQuestionID = 69,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 138,
                            ExamQuestionID = 69,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 139,
                            ExamQuestionID = 70,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 140,
                            ExamQuestionID = 70,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 151,
                            ExamQuestionID = 76,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 152,
                            ExamQuestionID = 76,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 153,
                            ExamQuestionID = 77,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 154,
                            ExamQuestionID = 77,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 155,
                            ExamQuestionID = 78,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 156,
                            ExamQuestionID = 78,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 157,
                            ExamQuestionID = 79,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 158,
                            ExamQuestionID = 79,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 159,
                            ExamQuestionID = 80,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 160,
                            ExamQuestionID = 80,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 171,
                            ExamQuestionID = 86,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 172,
                            ExamQuestionID = 86,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 173,
                            ExamQuestionID = 87,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 174,
                            ExamQuestionID = 87,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 175,
                            ExamQuestionID = 88,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 176,
                            ExamQuestionID = 88,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 177,
                            ExamQuestionID = 89,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 178,
                            ExamQuestionID = 89,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 179,
                            ExamQuestionID = 90,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 180,
                            ExamQuestionID = 90,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 191,
                            ExamQuestionID = 96,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 192,
                            ExamQuestionID = 96,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 193,
                            ExamQuestionID = 97,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 194,
                            ExamQuestionID = 97,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 195,
                            ExamQuestionID = 98,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 196,
                            ExamQuestionID = 98,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 197,
                            ExamQuestionID = 99,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 198,
                            ExamQuestionID = 99,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        },
                        new
                        {
                            ID = 199,
                            ExamQuestionID = 100,
                            IsCorrectAnswer = false,
                            Text = "Answer 1"
                        },
                        new
                        {
                            ID = 200,
                            ExamQuestionID = 100,
                            IsCorrectAnswer = true,
                            Text = "Answer 2"
                        });
                });

            modelBuilder.Entity("Task.BLL.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasAlternateKey("Email");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "STD1",
                            Email = "student1@test.com",
                            Name = "Student 1",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 2,
                            Code = "STD2",
                            Email = "student2@test.com",
                            Name = "Student 2",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 3,
                            Code = "STD3",
                            Email = "student3@test.com",
                            Name = "Student 3",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 4,
                            Code = "STD4",
                            Email = "student4@test.com",
                            Name = "Student 4",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 5,
                            Code = "STD5",
                            Email = "student5@test.com",
                            Name = "Student 5",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 6,
                            Code = "STD6",
                            Email = "student6@test.com",
                            Name = "Student 6",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 7,
                            Code = "STD7",
                            Email = "student7@test.com",
                            Name = "Student 7",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 8,
                            Code = "STD8",
                            Email = "student8@test.com",
                            Name = "Student 8",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 9,
                            Code = "STD9",
                            Email = "student9@test.com",
                            Name = "Student 9",
                            Password = "P@ssw0rd"
                        },
                        new
                        {
                            ID = 10,
                            Code = "STD10",
                            Email = "student10@test.com",
                            Name = "Student 10",
                            Password = "P@ssw0rd"
                        });
                });

            modelBuilder.Entity("Task.BLL.Models.StudentExam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentExam");
                });

            modelBuilder.Entity("Task.BLL.Models.StudentExamAnswer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExamQuestionID")
                        .HasColumnType("int");

                    b.Property<bool>("ISCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("MultipleChoiceQuestionAnswerID")
                        .HasColumnType("int");

                    b.Property<int>("StudentExamID")
                        .HasColumnType("int");

                    b.Property<bool>("TrueOrFalseAnswer")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ExamQuestionID");

                    b.HasIndex("MultipleChoiceQuestionAnswerID");

                    b.HasIndex("StudentExamID");

                    b.ToTable("StudentExamAnswer");
                });

            modelBuilder.Entity("Task.BLL.Models.ExamQuestion", b =>
                {
                    b.HasOne("Task.BLL.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Task.BLL.Models.MultipleChoiceQuestionAnswer", b =>
                {
                    b.HasOne("Task.BLL.Models.ExamQuestion", "ExamQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("ExamQuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("Task.BLL.Models.StudentExam", b =>
                {
                    b.HasOne("Task.BLL.Models.Exam", "Exam")
                        .WithMany("Students")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Task.BLL.Models.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Task.BLL.Models.StudentExamAnswer", b =>
                {
                    b.HasOne("Task.BLL.Models.ExamQuestion", "ExamQuestion")
                        .WithMany("StudentExamAnswers")
                        .HasForeignKey("ExamQuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Task.BLL.Models.MultipleChoiceQuestionAnswer", "MultipleChoiceQuestionAnswer")
                        .WithMany("StudentExamAnswers")
                        .HasForeignKey("MultipleChoiceQuestionAnswerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task.BLL.Models.StudentExam", "StudentExam")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("StudentExamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamQuestion");

                    b.Navigation("MultipleChoiceQuestionAnswer");

                    b.Navigation("StudentExam");
                });

            modelBuilder.Entity("Task.BLL.Models.Exam", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Task.BLL.Models.ExamQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("StudentExamAnswers");
                });

            modelBuilder.Entity("Task.BLL.Models.MultipleChoiceQuestionAnswer", b =>
                {
                    b.Navigation("StudentExamAnswers");
                });

            modelBuilder.Entity("Task.BLL.Models.Student", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Task.BLL.Models.StudentExam", b =>
                {
                    b.Navigation("ExamAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
